apiVersion: v1
kind: ConfigMap
metadata:
  name: java-api
data:
  LOG_LEVEL: "INFO"
  message.txt: |
    <html><body>
      <h1>
        Hello from Kubernetes version 2
      </h1>
      <p>
        Served through configmap and ingress
      </p>
    </body></html>
