apiVersion: v1
kind: Pod
metadata:
  name: java
spec:
  containers:
    - name: java
      image: nachomillangarcia/ayesa-java-api
      ports:
        - containerPort: 8080
      volumeMounts:
        - mountPath: /persistent
          name: test-volume
  volumes:
    - name: test-volume
      persistentVolumeClaim:
        claimName: local-hostpath-pvc
