prometheus:
  prometheusSpec:
    serviceMonitorSelector: {}
    serviceMonitorSelectorNilUsesHelmValues: false
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: openebs-hostpath
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 10Gi

    thanosImage:
      registry: quay.io
      repository: thanos/thanos
      tag: v0.39.2
      sha: ""
    thanos:
      objectStorageConfig:
        secret:
          type: S3
          config:
            bucket: thanos-formadoresit
            endpoint: s3.eu-central-1.amazonaws.com
            region: eu-central-1
          # access_key: 
          # secret_key:


  service:
    type: NodePort
  thanosService:
    enabled: true
  thanosServiceMonitor:
    enabled: true
    interval: "1m"

additionalPrometheusRulesMap:
  my-node-requests.rules:
    groups:
      - name: node-requests.rules
        rules:
        - record: node:memory_requests:ratio
          expr: |-
            sum by (node) (kube_pod_container_resource_requests{resource="memory"}) 

            / on(node)

            kube_node_status_allocatable{resource="memory"}

            * 100
  my-node-requests-alerts:
    groups:
      - name: node-requests-alerts
        rules:
        - alert: NodeMemoryRequestsHigh
          annotations:
            description: |
              {{ $labels.node }} node memory requests are over 4%, currently at {{ $value }}%
            summary: Node has high memory requests
          expr: node:memory_requests:ratio > 4
          for: 5m
          labels:
            severity: warning
            node: |-
              {{ $labels.node }}

alertmanager:
  alertmanagerSpec:
    replicas: 2
  service:
    type: NodePort

  config:
    global:
      resolve_timeout: 5m
      http_config:
        follow_redirects: true
        enable_http2: true
    route:
      receiver: "default"  # Fallback Receiver if no routes are matched
      continue: false
      routes:
      - receiver: "null"
        matchers:
        - alertname="Watchdog"
        continue: false
      - receiver: "teamA"
        matchers:
        - namespace="default"
        continue: false
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 12h
    inhibit_rules:
    - source_matchers:
      - severity="critical"
      target_matchers:
      - severity=~"warning|info"
      equal:
      - namespace
      - alertname
    - source_matchers:
      - severity="warning"
      target_matchers:
      - severity="info"
      equal:
      - namespace
      - alertname
    - source_matchers:
      - alertname="InfoInhibitor"
      target_matchers:
      - severity="info"
      equal:
      - namespace
    - target_matchers:
      - alertname="InfoInhibitor"
    receivers:
    - name: "default"
    - name: "teamA"
    - name: "null"
    templates:
    - /etc/alertmanager/config/*.tmpl

grafana:
  service: 
    type: NodePort
    nodePort: 30091
  persistence:
    enabled: true
    storageClassName: openebs-hostpath


thanosRuler:
  enabled: true
  thanosRulerSpec:
    objectStorageConfig:
      secret:
        type: S3
        config:
          bucket: thanos-formadoresit
          endpoint: s3.eu-central-1.amazonaws.com
          region: eu-central-1
          # access_key: 
          # secret_key: 
    queryEndpoints:
      - "dnssrv+_http._tcp.thanos-query.monitoring.svc.cluster.local"