apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch
  namespace: elastic
spec:
  monitoring:  # Add this section for stack monitoring
    metrics:
      elasticsearchRefs:
      - name: elasticsearch  # Your monitoring ES cluster name
        namespace: elastic  # Adjust if in a different namespace
    logs:
      elasticsearchRefs:
      - name: elasticsearch  # Your monitoring ES cluster name
        namespace: elastic  # Adjust if in a different namespace
  version: 9.2.0
  nodeSets:
  - name: default
    count: 1
    config:
      node.store.allow_mmap: false