apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana
  namespace: elastic
spec:
  version: 9.2.0
  count: 1
  monitoring:
    metrics:
      elasticsearchRefs:
      - name: elasticsearch  # Your monitoring ES cluster name
        namespace: elastic  # Adjust if in a different namespace
    logs:
      elasticsearchRefs:
      - name: elasticsearch  # Your monitoring ES cluster name
        namespace: elastic  # Adjust if in a different namespace
  elasticsearchRef:
    name: elasticsearch
  http:
      service:
        spec:
          type: NodePort
          ports:
            - port: 5601
              nodePort: 32601
              name: https
