apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
data:
  LOG_LEVEL: "INFO"
  foo: bar
  myvar: myvalue
  message.txt: |
    <html><body>
      <h1>
        Hello from Kubernetes version 3
      </h1>
      <p>
        Served through configmap and ingress
      </p>
    </body></html>