{{- $protocol := .Values.protocol }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- range $name, $value := .Values.deployment.annotations }}
    {{ $name }}: {{ $value | upper | quote }}
    {{- end }}    
spec:
  {{- with .Values.deployment }}
  replicas: {{ .replicas | default 1 }}
  strategy: 
    type: {{ .strategy }}
  {{- end }} 

    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: api-java
  template:  
    metadata:
      labels:
        app: api-java
    spec:
      containers:
        - name: api
          image: nachomillangarcia/ayesa-java-api:{{ .Values.tag }}
          ports:
          {{- if eq $protocol "http" }}
          - containerPort: 8080
            name: http
          {{- else if eq $protocol "https"}}
          - containerPort: 8443
            name: https
          {{- else -}}
          {{- end }}
          
          volumeMounts:
          {{- range .Values.volumeMounts }}
          - name: {{ .name | quote }}
            mountPath: {{ .path | quote }}
          {{- end }}

          resources:
          {{- toYaml .Values.deployment.resources | nindent 12 }}

      {{- if .Values.configMap.enabled }}
      volumes:
      {{- range $conf := .Values.configMap.configs }}
        - name: {{ $conf.name }}
          configMap:
            name: {{ $.Release.Name }}-configmap
      {{- end }}
      
      {{- end }}